Class INSPUR.JKS.TJ.Entities.AbstractEntity Extends (%Persistent, %Populate, %XML.Adaptor, %JSON.Adaptor) [ Abstract ]
{

Storage Default
{
<Data name="AbstractEntityDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^INSPUR.JKS.T897.AbstractEntityD</DataLocation>
<DefaultData>AbstractEntityDefaultData</DefaultData>
<IdLocation>^INSPUR.JKS.T897.AbstractEntityD</IdLocation>
<IndexLocation>^INSPUR.JKS.T897.AbstractEntityI</IndexLocation>
<StreamLocation>^INSPUR.JKS.T897.AbstractEntityS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
