Class DocumentSearch.Message.GetEncountersStreamResponse Extends Ens.Response
{
	Property ContentStream As %Stream.GlobalCharacter;
Storage Default
{
<Data name="GetEncountersStreamResponseDefaultData">
<Subscript>"GetEncountersStreamResponse"</Subscript>
<Value name="1">
<Value>ContentStream</Value>
</Value>
</Data>
<DefaultData>GetEncountersStreamResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}